version: "3"
services:
  bonus-service:
    container_name: bonus-service
    build:
      context: .
      dockerfile: ./services/bonusService/Dockerfile
    environment:
      NODE_ENV: development
      PORT: 8180
    ports:
      - "8180:8180"

  airport-service:
    container_name: airport-service
    build:
      context: .
      dockerfile: ./services/airportService/Dockerfile
    environment:
      NODE_ENV: development
      PORT: 8280
    ports:
      - "8280:8280"

  flight-service:
    container_name: flight-service
    build:
      context: .
      dockerfile: ./services/flightService/Dockerfile
    environment:
      NODE_ENV: development
      PORT: 8380
    ports:
      - "8380:8380"

  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    container_name: "rabbitmq"
    ports:
      - 5673:5672
      - 15673:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - rabbitmq_nodejs

  ticket-service:
    container_name: ticket-service
    build:
      context: .
      dockerfile: ./services/ticketService/Dockerfile
    environment:
      NODE_ENV: development
      PORT: 8480
    ports:
      - "8480:8480"

  session-service:
    container_name: session-service
    build:
      context: .
      dockerfile: ./services/sessionService/Dockerfile
    environment:
      NODE_ENV: development
      PORT: 8580
    ports:
      - "8580:8580"

  statistic-service:
    container_name: statistic-service
    build:
      context: .
      dockerfile: ./services/statisticService/Dockerfile
    environment:
      NODE_ENV: development
      PORT: 8680
    ports:
      - "8680:8680"

  # gateway-service:
  #   container_name: gateway-service
  #   build:
  #     context: .
  #     dockerfile: ./services/gatewayService/Dockerfile
  #   environment:
  #     NODE_ENV: development
  #     PORT: 8780
  #   ports:
  #     - "8780:8780"

networks:
  rabbitmq_nodejs:
    driver: bridge

volumes:
  db-data:
