version: "3"
services:
  bonus-service:
    container_name: bonus-service
    build:
      context: .
      dockerfile: ./services/bonusService/Dockerfile
    environment:
      NODE_ENV: development
      PORT: 8180
    ports:
      - "8180:8180"

  airport-service:
    container_name: airport-service
    build:
      context: .
      dockerfile: ./services/airportService/Dockerfile
    environment:
      NODE_ENV: development
      PORT: 8280
    ports:
      - "8280:8280"

  flight-service:
    container_name: flight-service
    build:
      context: .
      dockerfile: ./services/flightService/Dockerfile
    environment:
      NODE_ENV: development
      PORT: 8380
    ports:
      - "8380:8380"

  ticket-service:
    container_name: ticket-service
    build:
      context: .
      dockerfile: ./services/ticketService/Dockerfile
    environment:
      NODE_ENV: development
      PORT: 8480
    ports:
      - "8480:8480"

volumes:
  db-data:
