version: '3'
services:
  warranty-service:
    container_name: warranty-service
    build:
      context: .
      dockerfile: ./services/warrantyService/Dockerfile
    environment:
      NODE_ENV: development
      PORT: 8180
    ports:
      - '8180:8180'

  warehouse-service:
    container_name: warehouse-service
    build:
      context: .
      dockerfile: ./services/warehouseService/Dockerfile
    environment:
      NODE_ENV: development
      PORT: 8280
    ports:
      - '8280:8280'

  order-service:
    container_name: order-service
    build:
      context: .
      dockerfile: ./services/orderService/Dockerfile
    environment:
      NODE_ENV: development
      PORT: 8380
    ports:
      - '8380:8380'

  store-service:
    container_name: store-service
    build:
      context: .
      dockerfile: ./services/storeService/Dockerfile
    environment:
      NODE_ENV: development
      PORT: 8480
    ports:
      - '8480:8480'

volumes:
  db-data:
